version: 2

defaults: &defaults
  docker:
    - image: circleci/node:lts-browsers

step_restore_cache: &restore_cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "package-lock.json" }}
      - v1-dependencies-

step_install_deps: &install_deps
  run:
    name: Install Dependencies
    command: npm install

step_save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package-lock.json" }}

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      - run: npm test

workflows:
  version: 2
  ci:
    jobs:
      - test
